# concat
# use of '//'
print("He"+"y"+" this is go"+"ing to be a ve"+"ry Weird code"+" Bcz this is writ"+"ten with +"+"\nany ways good bye")
print()
print()
print()
print()
print("\nSo u are still here huh!!!ok fine let us do some work then")
input("Do you want to print hello 5 times if yes then just press enter")
print("\nHello"*5)
print("Let us do some pythonic maths")
print(2+3)
print(2-3)
print(2*3)
print(2/3)
print(2//3)
naam =" Larry "
print(naam)
print("Hi"+" "+naam)
print("Let us ask the user his/her name")
name=input("What is ur name my dear user?")
print("HI!!!"+ name)
nu=input("Enter first number")
no=input("Enter the second number")
sum=int(no)+int(nu)
print(sum)
print("It is connecting the two numbers this is a prblm",end=" ")
print("Hang on let us find the solution to this in other commit")
print("So to sum up the two numbers you must write the line no as mentioned in the comments")
#Comments:-Line number 25
