#concat # use of '//'
print("He"+"y"+" this is go"+"ing to be a ve"+"ry Weird code"+" Bcz this is writ"+"ten with +"+"\nany ways good bye")
print()
print()
print()
print()
print("\nSo u are still here huh!!!ok fine let us do some work then")
input("Do you want to print hello 5 times if yes then just press enter")
print("\nHello"*5)
print("Let us do some pythonic maths")
print(2+3)
print(2-3)
print(2*3)
print(2/3)
print(2//3)