print("Hey there")
input("Please Press Enter to win this game")
print("Sorry You lost the game")
print("Don't follow",end=""" """)
print("My Instructions again",end=""" """)
input("Please leave this game by pressing the enter")
print("HUH!!!you dumb,you again follow my instruction ohk then bieee")
print("\a")
print("\nSpecial Thanks to\\Mr.Yash Saxena\\")
print("\tSpecial thanks to u buddy")
input("Press Enter and say good bye")
print("HHH")