import random
print("Reading the file....")
t=open("/root/Desktop/python","r")
print(t.read(1))
print(t.read(2))
t.close()
p=open("/root/Desktop/python","r")
print(p.read())
p.close()
v=open("/root/Desktop/python","r")
print(v.readline())
print(v.readline())
v.close()
b=open("/root/Desktop/python","r")
print(b.readline(2))
b.close()
print("\nNow we are going to read the lines of this file using a list and i will try to perform some operations on it....")
h=open("/root/Desktop/python","r")
l=h.readlines()
print(l)
print(random.choice(l))
print("Sorting the elements:")
l.sort()
print(l)
print("removing the first element")
del l[0]
print(l)
h.close()
print("Now we are going to perfrom some write operation on the same file\n")
n=open("/root/Desktop/python","w")
n.write("Hello\n")
n.write("My self\n")
n.write("Yash Saxena\n")
n.close()
print("Now reading the file after writing some data on it:\n")
g=open("/root/Desktop/python","r")
print(g.read())
g.close()
print("Wait,where is my old data ohh Fu*k the write() function overwrite the data!!!")
print("Now we are going to wipe out the data again but this time we will write the data using a list")
line=["Hey there\n","My self\n","Yash Saxena\n"]
c=open("/root/Desktop/python","w")
c.writelines(line)
print("Reading the new data of the file:\n")
print(c.read())
#This program will produce an error because at last file is empty and there is nothing to read from the file!!!
